MyBook/Controllers/AuthorsController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBook.Core.Models;
using MyBook.Core.ViewModel;
using MyBook.Data;
using MyBook.Filter;

namespace MyBook.Controllers
{
    public class AuthorsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public AuthorsController(ApplicationDbContext context , IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var authors = _context.Authors.AsNoTracking().ToList();
            var authorsvm = _mapper.Map<IEnumerable<AuthorVM>>(authors);
            return View(authorsvm);
        }
        [HttpGet]
        [AjaxOnly]
        public IActionResult Create()
        {
            return PartialView("_Form");
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(AuthorViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var author = _mapper.Map<Author>(model);

            _context.Authors.Add(author);
            _context.SaveChanges();

            var authorvm = _mapper.Map<AuthorVM>(author);
            return PartialView("_ModalRow", authorvm);
        }
        [HttpGet]
        [AjaxOnly]
        public IActionResult Edit(int id)
        {
            var author = _context.Authors.Find(id);
            if (author is null)
                return NotFound();

            var authorvm = _mapper.Map<AuthorViewModel>(author);
            return PartialView("_Form", authorvm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(AuthorViewModel model)
        {
            var author = _context.Authors.Find(model.Id);
            if (author is null)
                return BadRequest();

            author = _mapper.Map(model, author);
            author.LastUpdatedOn = DateTime.Now;

            _context.Authors.Update(author);
            _context.SaveChanges();

            var authorVM = _mapper.Map<AuthorVM>(author);
            return PartialView("_ModalRow", authorVM);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult ToggleStatus(int id)
        {
            var author = _context.Authors.Find(id);
            if (author is null)
                return NotFound();

            author.IsDeleted = !author.IsDeleted;
            author.LastUpdatedOn = DateTime.Now;

            _context.Authors.Update(author);
            _context.SaveChanges();

            return Ok(author.LastUpdatedOn.ToString());
        }

        public IActionResult IsAllowed(AuthorViewModel model)
        {
            var author = _context.Authors.SingleOrDefault(a => a.Name == model.Name);
            var IsAllowed = author is null || author.Id.Equals(model.Id);
            return Json(IsAllowed);
        }

    }
}

MyBook/Controllers/CategoriesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBook.Core.Models;
using MyBook.Core.ViewModel;
using MyBook.Data;
using MyBook.Filter;

namespace MyBook.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IMapper _mapper;

        public CategoriesController(ApplicationDbContext context , IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var books = _context.Categories.AsNoTracking().ToList();
            var ViewModal = _mapper.Map<IEnumerable<CategoryVM>>(books);
            return View(ViewModal);
        }
        [HttpGet]
        [AjaxOnly]
        public IActionResult Create()
        {
            return PartialView("_Form");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryViewModel model)
        {
            if (!ModelState.IsValid)
                return BadRequest();

            var book = _mapper.Map<Category>(model);

            
            _context.Categories.Add(book);
            _context.SaveChanges();

            var bookVM = _mapper.Map<CategoryVM>(book);
            return PartialView("_ModalRow", bookVM);
        }
        [HttpGet]
        [AjaxOnly]
        public IActionResult Edit(int id)
        {
            var book = _context.Categories.Find(id);
            if (book is null)
                return NotFound();

            var category = _mapper.Map<CategoryViewModel>(book);
            return PartialView("_Form" , category);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CategoryViewModel model)
        {
            var book = _context.Categories.Find(model.Id);
            if (book is null)
                return BadRequest();

            book = _mapper.Map(model, book);
            book.LastUpdatedOn = DateTime.Now;

            _context.Categories.Update(book);
            _context.SaveChanges();

            var bookVM = _mapper.Map<CategoryVM>(book);
            return PartialView("_ModalRow", bookVM);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult ToggleStatus(int id)
        {
            var book = _context.Categories.Find(id);
            if (book is null)
                return NotFound();

            book.IsDeleted = !book.IsDeleted;
            book.LastUpdatedOn = DateTime.Now;

            _context.Categories.Update(book);
            _context.SaveChanges();

            return Ok(book.LastUpdatedOn.ToString());
        }

        public IActionResult IsAllowed(CategoryViewModel model)
        {
            var category = _context.Categories.SingleOrDefault(c => c.Name == model.Name);
            var IsAllowed = category is null || category.Id.Equals(model.Id);
            return Json(IsAllowed);
        }

    }
}

MyBook/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyBook.Core.ViewModel;
using System.Diagnostics;

namespace MyBook.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyBook/Views/Authors/Index.cshtml
@model IEnumerable<AuthorVM>

@{
    ViewData["Title"] = "Author";
}
@section Style{
    <partial name="_DataTablesCss" />
}
<div class="m-5">
    <div class="card">
        <div class="card-header d-flex  justify-content-between">
            <h5 class="card-title text-muted">
                <svg width="24" height="24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" data-v-481ddfc4="">
                    <path d="M5.288 2.5a.476.476 0 0 0-.45.321l-.472 1.371H2.803a.477.477 0 0 0-.288.856l1.267.96-.43 1.374a.476.476 0 0 0 .74.523l1.196-.895 1.195.895a.476.476 0 0 0 .74-.523l-.428-1.373 1.267-.961a.477.477 0 0 0-.289-.856H6.21l-.472-1.37a.476.476 0 0 0-.45-.322Zm4.962 2a.75.75 0 1 0 0 1.5h10.5a.75.75 0 1 0 0-1.5h-10.5ZM5.288 9.251a.476.476 0 0 0-.45.32l-.47 1.371H2.802a.477.477 0 0 0-.287.856l1.266.96-.428 1.374a.476.476 0 0 0 .739.523l1.195-.895 1.196.895a.476.476 0 0 0 .74-.523l-.43-1.373 1.268-.961a.474.474 0 0 0 .162-.531.475.475 0 0 0-.45-.325H6.208l-.47-1.37a.475.475 0 0 0-.45-.321Zm4.962 1.999a.751.751 0 1 0 0 1.5h10.5a.751.751 0 1 0 0-1.5h-10.5ZM5.288 16a.476.476 0 0 0-.45.321l-.472 1.371H2.803a.477.477 0 0 0-.288.856l1.267.96-.43 1.374a.476.476 0 0 0 .74.523l1.196-.895 1.195.895a.476.476 0 0 0 .74-.523l-.428-1.373 1.267-.961a.477.477 0 0 0-.289-.856H6.21l-.472-1.37a.476.476 0 0 0-.45-.322Zm4.962 2a.751.751 0 1 0 0 1.5h10.5a.751.751 0 1 0 0-1.5h-10.5Z">
                    </path>
                </svg>
                Authors
            </h5>
            <span>
                <a href="Javascript:;" class="btn btn-primary btn-sm js-render-modal"
                   data-title="Add Author" data-url="/Authors/Create">
                    Add Author
                </a>
            </span>
        </div>
        <div class="card-body mt-2">
            <table class="table table-hover text-center table-bordered">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Status</th>
                        <th>Created On</th>
                        <th>Last Updated On</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var author in Model)
                    {
                        <partial name="_ModalRow" model="@author" />
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@Html.AntiForgeryToken()
@section CustomScripts{
    <partial name="_DataTablesJs" />
}

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MyBook/Views/Authors/_Form.cshtml
@model AuthorViewModel

<form asp-action="@(Model?.Id > 0 ? "Edit" : "Create")"
      data-ajax-method="post"
      data-ajax="true"
      data-ajax-begin="onModalBegin"
      data-ajax-success="onModalSuccess"
      data-ajax-failure="showErrorMessage"
      data-ajax-complete="onModalComplete">
    @if (Model?.Id > 0)
    {
        <input type="hidden" asp-for="Id" />
    }
    <div class="form-floating mb-2">
        <input type="text" class="form-control" asp-for="Name" placeholder="Author Name">
        <label asp-for="Name" class="text-muted">Author Name</label>
    </div>
    <span asp-validation-for="Name" class="text-danger"></span>
    <partial name="_ModalFooter" />
</form>

MyBook/Views/Authors/_ModalRow.cshtml
@model AuthorVM
<tr>
    <td>@Model.Name</td>
    <td>
        <span class="badge rounded-pill @(Model.IsDeleted ? "text-bg-danger" : "text-bg-primary") js-status">
            @(Model.IsDeleted ? "Deleted" : "Available")
        </span>
    </td>
    <td>@Model.CreatedOn</td>
    <td class="js-updated-on">@Model.LastUpdatedOn</td>
    <td>
        <div class="btn-group">
            <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-activity" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M6 2a.5.5 0 0 1 .47.33L10 12.036l1.53-4.208A.5.5 0 0 1 12 7.5h3.5a.5.5 0 0 1 0 1h-3.15l-1.88 5.17a.5.5 0 0 1-.94 0L6 3.964 4.47 8.171A.5.5 0 0 1 4 8.5H.5a.5.5 0 0 1 0-1h3.15l1.88-5.17A.5.5 0 0 1 6 2Z" />
                </svg>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a href="Javascript:;" class="dropdown-item js-render-modal"
                       data-title="Edit Author" data-url="/Authors/Edit/@Model.Id" data-updated="true">
                        Edit
                    </a>
                </li>
                <li>
                    <a class="dropdown-item js-toggle-status" href="JavaScript:;" data-url="/Authors/Togglestatus/@Model.Id">
                        Toggle Status
                    </a>
                </li>
            </ul>
        </div>
    </td>
</tr>

MyBook/Views/Categories/Index.cshtml
@model IEnumerable<CategoryVM>

@{
    ViewData["Title"] = "Category";
}
@section Style{
    <partial name="_DataTablesCss" />
}
<div class="m-5">
    <div class="card">
        <div class="card-header d-flex  justify-content-between">
            <h5 class="card-title text-muted">
                <svg width="24" height="24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" data-v-481ddfc4="">
                    <path d="M5.288 2.5a.476.476 0 0 0-.45.321l-.472 1.371H2.803a.477.477 0 0 0-.288.856l1.267.96-.43 1.374a.476.476 0 0 0 .74.523l1.196-.895 1.195.895a.476.476 0 0 0 .74-.523l-.428-1.373 1.267-.961a.477.477 0 0 0-.289-.856H6.21l-.472-1.37a.476.476 0 0 0-.45-.322Zm4.962 2a.75.75 0 1 0 0 1.5h10.5a.75.75 0 1 0 0-1.5h-10.5ZM5.288 9.251a.476.476 0 0 0-.45.32l-.47 1.371H2.802a.477.477 0 0 0-.287.856l1.266.96-.428 1.374a.476.476 0 0 0 .739.523l1.195-.895 1.196.895a.476.476 0 0 0 .74-.523l-.43-1.373 1.268-.961a.474.474 0 0 0 .162-.531.475.475 0 0 0-.45-.325H6.208l-.47-1.37a.475.475 0 0 0-.45-.321Zm4.962 1.999a.751.751 0 1 0 0 1.5h10.5a.751.751 0 1 0 0-1.5h-10.5ZM5.288 16a.476.476 0 0 0-.45.321l-.472 1.371H2.803a.477.477 0 0 0-.288.856l1.267.96-.43 1.374a.476.476 0 0 0 .74.523l1.196-.895 1.195.895a.476.476 0 0 0 .74-.523l-.428-1.373 1.267-.961a.477.477 0 0 0-.289-.856H6.21l-.472-1.37a.476.476 0 0 0-.45-.322Zm4.962 2a.751.751 0 1 0 0 1.5h10.5a.751.751 0 1 0 0-1.5h-10.5Z">
                    </path>
                </svg>
                Categories
            </h5>
            <span>
                <a href="Javascript:;" class="btn btn-primary btn-sm js-render-modal"
                   data-title="Add Category" data-url="/Categories/Create">
                    Add Book
                </a>
            </span>
        </div>
        <div class="card-body mt-2">
            @if (!Model.Any())
            {
                <div class="alert alert-warning text-center" role="alert">
                    No Categories Found !
                </div>
            }
            else
            {
                <table class="table table-hover text-center table-bordered">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Created On</th>
                            <th>Last Updated On</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var category in Model)
                        {
                            <partial name="_ModalRow" model="@category" />
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>

@Html.AntiForgeryToken()
@section CustomScripts{
    <partial name="_DataTablesJs" />
}

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

MyBook/Views/Categories/_Form.cshtml
@model CategoryViewModel

<form asp-action="@(Model?.Id > 0 ? "Edit" : "Create")"
    data-ajax-method="post"
    data-ajax="true"
    data-ajax-begin="onModalBegin"
      data-ajax-success="onModalSuccess"
    data-ajax-failure="showErrorMessage"
    data-ajax-complete="onModalComplete">
    @if (Model?.Id > 0)
    {
        <input type="hidden" asp-for="Id" />
    }
    <div class="form-floating mb-2">
        <input type="text" class="form-control" asp-for="Name" placeholder="Category Name">
        <label asp-for="Name" class="text-muted">Category Name</label>
    </div>
    <span asp-validation-for="Name" class="text-danger"></span>
    <partial name="_ModalFooter"/>
</form>

MyBook/Views/Categories/_ModalRow.cshtml
@model CategoryVM
<tr>
    <td>@Model.Name</td>
    <td>
        <span class="badge rounded-pill @(Model.IsDeleted ? "text-bg-danger" : "text-bg-primary") js-status">
            @(Model.IsDeleted ? "Deleted" : "Available")
        </span>
    </td>
    <td>@Model.CreatedOn</td>
    <td class="js-updated-on">@Model.LastUpdatedOn</td>
    <td>
        <div class="btn-group">
            <button class="btn btn-outline-primary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-activity" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M6 2a.5.5 0 0 1 .47.33L10 12.036l1.53-4.208A.5.5 0 0 1 12 7.5h3.5a.5.5 0 0 1 0 1h-3.15l-1.88 5.17a.5.5 0 0 1-.94 0L6 3.964 4.47 8.171A.5.5 0 0 1 4 8.5H.5a.5.5 0 0 1 0-1h3.15l1.88-5.17A.5.5 0 0 1 6 2Z" />
                </svg>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a href="Javascript:;" class="dropdown-item js-render-modal"
                       data-title="Edit Catecory" data-url="/Categories/Edit/@Model.Id" data-updated="true">
                        Edit
                    </a>
                </li>
                <li>
                    <a class="dropdown-item js-toggle-status" href="JavaScript:;" data-url="/Categories/Togglestatus/@Model.Id">
                        Toggle Status
                    </a>
                </li>
            </ul>
        </div>
    </td>
</tr>

MyBook/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home";
}

<div class="text-center m-5">
    <img width="100" height="100" src="https://img.icons8.com/ultraviolet/80/literature--v1.png" alt="literature--v1" />
    <h1 class="display-4">Bookify App</h1>
</div>

MyBook/Views/Shared/_DataTablesCss.cshtml
<link href="~/lib/datatables/css/datatables.bootstrap4.min.css" rel="stylesheet" />
<link href="~/lib/datatables.net-buttons-bs4/buttons.bootstrap4.min.css" rel="stylesheet" />

MyBook/Views/Shared/_DataTablesJs.cshtml
<script src="~/lib/datatables/js/jquery.datatables.min.js"></script>
<script src="~/lib/datatables/js/datatables.bootstrap4.min.js"></script>
<script src="~/datatables-buttons/js/datatables.buttons.min.js"></script>
@*<script src="~/datatables.net-buttons-bs4/buttons.bootstrap4.min.js"></script>*@
<script src="~/lib/jszip/jszip.min.js"></script>
<script src="~/lib/pdfmake/pdfmake.min.js"></script>
<script src="~/lib/pdfmake/vfs_fonts.min.js"></script>
<script src="~/lib/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/lib/datatables-buttons/js/buttons.print.min.js"></script>

MyBook/Views/Shared/_Footer.cshtml
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
          
        </div>
    </div>
</footer>

MyBook/Views/Shared/_FormModal.cshtml
<!-- Modal -->
<div class="modal fade" id="Modal" tabindex="-1" aria-labelledby="ModalLabel" aria-hidden="true" style="backdrop-filter:blur(5px);">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="ModalLabel">
                    @*Modal Title Will Be Rendered Here*@ Here 
                </h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @*Modal Body Will Be Renedered Here*@
            </div>
        </div>
    </div>
</div>

MyBook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>@ViewData["Title"] - MyBook</title>
    <link rel="icon" href="~/icons8-book-cute-outline-32.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
    <link rel="stylesheet" href="~/lib/sweetalert2/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/lib/animate.css/animate.min.css" />
    <link rel="canonical" href="Https://preview.keenthemes.com/ceres-html-pro">

        @await RenderSectionAsync("Style", required: false)

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyBook.styles.css" asp-append-version="true" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed page-loading">
    
    <div class="page-loader">
        <span class="spinner-border text-bg-primary" role="status">
            <span class="visually-hidden">Loading...</span>
        </span>
    </div>

    <partial name="_Nav" />
    <div id="layoutSidenav">
        <partial name="_SideBar" />
        @*Render Body*@
        <div id="layoutSidenav_content">
            <main role="main">
                <div class="container-fluid px-4">
                    @RenderBody()
                </div>
            </main>
            <partial name="_Footer" />
        </div>

        <partial name="_FormModal"/>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/lib/bootbox.js/bootbox.min.js"></script>
        <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
        @await RenderSectionAsync("CustomScripts", required: false)
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)

    </div>
</body>
</html>

MyBook/Views/Shared/_ModalFooter.cshtml
<div class="modal-footer p-1 px-0">
    <button type="button" class="btn btn-sm btn-secondary" data-bs-dismiss="modal">Close</button>

    <button type="submit" class="btn btn-primary me-10">
        <span class="indicator-label">
            Save
        </span>
        <span class="indicator-progress">
            Please wait... <span class="spinner-border spinner-border-sm align-middle ms-2"></span>
        </span>
    </button>

</div>

MyBook/Views/Shared/_Nav.cshtml
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand " href="Script:;">
        <img width="50" height="50" src="https://img.icons8.com/carbon-copy/100/literature.png" alt="literature" />
        My Book
    </a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <div class="input-group">
            <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#!">Settings</a></li>
                <li><a class="dropdown-item" href="#!">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#!">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>

MyBook/Views/Shared/_SideBar.cshtml
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">My Book</div>
                <a class="nav-link" asp-controller="Home" asp-action="Index" active-when="Home">
                    <div class="sb-nav-link-icon">
                        <img width="25" height="25" src="https://img.icons8.com/sf-ultralight/25/home.png" />
                    </div>
                    Home
                </a>
                <a class="nav-link" asp-controller="Categories" asp-action="Index" active-when="Categories">

                    <div class="sb-nav-link-icon">
                        <svg width="24" height="24" fill="currentColor" xmlns="http://www.w3.org/2000/svg" data-v-481ddfc4="">
                            <path d="M5.288 2.5a.476.476 0 0 0-.45.321l-.472 1.371H2.803a.477.477 0 0 0-.288.856l1.267.96-.43 1.374a.476.476 0 0 0 .74.523l1.196-.895 1.195.895a.476.476 0 0 0 .74-.523l-.428-1.373 1.267-.961a.477.477 0 0 0-.289-.856H6.21l-.472-1.37a.476.476 0 0 0-.45-.322Zm4.962 2a.75.75 0 1 0 0 1.5h10.5a.75.75 0 1 0 0-1.5h-10.5ZM5.288 9.251a.476.476 0 0 0-.45.32l-.47 1.371H2.802a.477.477 0 0 0-.287.856l1.266.96-.428 1.374a.476.476 0 0 0 .739.523l1.195-.895 1.196.895a.476.476 0 0 0 .74-.523l-.43-1.373 1.268-.961a.474.474 0 0 0 .162-.531.475.475 0 0 0-.45-.325H6.208l-.47-1.37a.475.475 0 0 0-.45-.321Zm4.962 1.999a.751.751 0 1 0 0 1.5h10.5a.751.751 0 1 0 0-1.5h-10.5ZM5.288 16a.476.476 0 0 0-.45.321l-.472 1.371H2.803a.477.477 0 0 0-.288.856l1.267.96-.43 1.374a.476.476 0 0 0 .74.523l1.196-.895 1.195.895a.476.476 0 0 0 .74-.523l-.428-1.373 1.267-.961a.477.477 0 0 0-.289-.856H6.21l-.472-1.37a.476.476 0 0 0-.45-.322Zm4.962 2a.751.751 0 1 0 0 1.5h10.5a.751.751 0 1 0 0-1.5h-10.5Z">
                            </path>
                        </svg>
                    </div>
                    Categories
                </a>
                <a class="nav-link" asp-controller="Authors" asp-action="Index" active-when="Authors">
                    <div class="sb-nav-link-icon">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
                            <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1h8Zm-7.978-1A.261.261 0 0 1 7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002a.274.274 0 0 1-.014.002H7.022ZM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4Zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0ZM6.936 9.28a5.88 5.88 0 0 0-1.23-.247A7.35 7.35 0 0 0 5 9c-4 0-5 3-5 4 0 .667.333 1 1 1h4.216A2.238 2.238 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816ZM4.92 10A5.493 5.493 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275ZM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0Zm3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4Z" />
                        </svg>
                    </div>
                    Authors
                </a>
            </div>
        </div>
    </nav>
</div>